name: "Install pip dependencies"
description: "Install Python dependencies from requirements.txt"

inputs:
  working-directory:
    description: "Directory containing requirements.txt"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      run: pip install -r requirements.txt
      shell: cmd
