name: "Install Python dependencies"
description: "Installs Python packages from requirements.txt"
inputs:
  working-dir:
    description: "Working directory with requirements.txt"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set working directory
      run: cd ${{ inputs.working-dir }}
      shell: cmd

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: cmd