name: "Deploy App"
description: "Deploy Python app with pm2"
inputs:
  working-dir:
    description: "Project folder"
    required: true
  env-name:
    description: "Deployment environment (dev, staging, etc)"
    required: true
  port:
    description: "Port to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Change to working directory
      run: cd ${{ inputs.working-dir }}
      shell: cmd

    - name: Add pm2 to PATH
      run: set PATH=C:\Users\marku\AppData\Roaming\npm;%PATH%
      shell: cmd

    - name: Echo deployment info
      run: echo "Deploying to ${{ inputs.env-name }} on port ${{ inputs.port }}"
      shell: cmd

    - name: Start app with pm2
      run: pm2 start app.py --name greetings-app-${{ inputs.env-name }} --interpreter python -- --port ${{ inputs.port }}
      working-directory: ${{ inputs.working-dir }}
      shell: cmd
