name: "Deploy Python App"
description: "Deploy app to environment with port"
inputs:
  working-dir:
    description: "Working directory"
    required: true
  env-name:
    description: "Environment name (dev, staging, preprod, prod)"
    required: true
  port:
    description: "Port number to run app on"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set working dir
      run: cd ${{ inputs.working-dir }}
      shell: cmd

    - name: Set path for pm2
      run: set PATH=%APPDATA%\npm;%PATH%
      shell: cmd

    - name: Start app with PM2
      shell: cmd
      working-directory: ${{ inputs.working-dir }}
      run: |
        echo "Deploying to ${{ inputs.env-name }} on port ${{ inputs.port }}"
        $env:PORT=${{ inputs.port }}
        pm2 start app.py --name greetings-app-${{ inputs.env-name }} --interpreter python -- --port ${{ inputs.port }}
