name: "Deploy Python App"
description: "Deploy the Python app to a given environment"
inputs:
  working-dir:
    description: "Working directory of the app"
    required: true
  env-name:
    description: "Deployment environment (e.g. dev, staging)"
    required: true
  port:
    description: "Port number"
    required: true
runs:
  using: "composite"
  steps:
    - name: Deploy app with PM2
      shell: cmd
      run: |
        set PATH=%APPDATA%\npm;%PATH%
        echo Deploying to ${{ inputs.environment }} on port ${{ inputs.port }}
        pm2 start app.py --name greetings-app-${{ inputs.environment }} --interpreter python -- --port ${{ inputs.port }}
