name: Pre-cleanup
description: Ensure PM2 is available and stop old processes
runs:
  using: "composite"
  steps:
    - name: Add PM2 to PATH manually
      run: |
        set "PATH=%APPDATA%\npm;%PATH%"
        where pm2
      shell: cmd
