name: "Pre-cleanup"
description: "Clean up previous PM2 processes"
runs:
  using: "composite"
  steps:
    - name: Clean up PM2 apps
      shell: cmd
      run: |
        where pm2 >nul 2>&1
        if %ERRORLEVEL% EQU 0 (
          echo PM2 found. Deleting all existing apps...
          pm2 delete all
        ) else (
          echo PM2 is not installed or not found in PATH
        )
