name: Python Microservice Delivery Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-deps
        with:
          working-dir: .

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          working-dir: .
          env-name: dev
          port: 7001

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          working-dir: .
          test-env: greetings_dev

  deploy-to-staging:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          working-dir: .
          env-name: staging
          port: 7002

  tests-on-staging:
    runs-on: self-hosted
    needs: deploy-to-staging
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          working-dir: .
          test-env: greetings_stg

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-staging
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          working-dir: .
          env-name: preprod
          port: 7003

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          working-dir: .
          test-env: greetings_preprod

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          working-dir: .
          env-name: prod
          port: 7004

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          working-dir: .
          test-env: greetings_prod
