name: Python Microservice Delivery Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Prepare all required actions
        uses: actions/checkout@v4

      - name: Run pre-cleanup
        uses: ./.github/actions/pre-cleanup

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings

      - name: Install Python dependencies
        uses: ./.github/actions/install-deps
        with:
          working-directory: greetings

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Run pre-cleanup
        uses: ./.github/actions/pre-cleanup
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - uses: ./.github/actions/deploy
        with:
          working-directory: greetings
          env-name: dev
          port: 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    env:
      FLASK_DEBUG: "false"
    steps:
    
      - name: Run pre-cleanup
        uses: ./.github/actions/pre-cleanup
        
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - name: Restart PM2 before tests
        shell: cmd
        working-directory: greetings
        run: |
          echo "Restarting app for dev..."
          $env:PORT=7001
          pm2 start app.py --name greetings-app-dev --interpreter python
          
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework
      - uses: ./.github/actions/test
        with:
          working-dir: test-framework
          test-env: greetings_dev

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:

      - name: Run pre-cleanup
        uses: ./.github/actions/pre-cleanup
        
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - uses: ./.github/actions/deploy
        with:
          working-dir: greetings
          env-name: staging
          port: 7002

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:

      - name: Run pre-cleanup
        uses: ./.github/actions/pre-cleanup
        
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - name: Restart PM2 before tests
        shell: cmd
        working-directory: greetings
        run: |
          echo "Restarting app for staging..."
          $env:PORT=7002
          pm2 start app.py --name greetings-app-staging --interpreter python
          
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework
      - uses: ./.github/actions/test
        with:
          working-dir: test-framework
          test-env: greetings_stg

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:

      - name: Run pre-cleanup
        uses: ./.github/actions/pre-cleanup
        
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - uses: ./.github/actions/deploy
        with:
          working-dir: greetings
          env-name: preprod
          port: 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:

      - name: Run pre-cleanup
        uses: ./.github/actions/pre-cleanup
        
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - name: Restart PM2 before tests
        shell: cmd
        working-directory: greetings
        run: |
          echo "Restarting app for preprod..."
          $env:PORT=7003
          pm2 start app.py --name greetings-app-preprod --interpreter python -f
          
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework
      - uses: ./.github/actions/test
        with:
          working-dir: test-framework
          test-env: greetings_preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:

      - name: Run pre-cleanup
        uses: ./.github/actions/pre-cleanup
        
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - uses: ./.github/actions/deploy
        with:
          working-dir: greetings
          env-name: prod
          port: 7004

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:

      - name: Run pre-cleanup
        uses: ./.github/actions/pre-cleanup
        
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - name: Restart PM2 before tests
        shell: cmd
        working-directory: greetings
        run: |
          echo "Restarting app for prod..."
          $env:PORT=7004
          pm2 start app.py --name greetings-app-prod --interpreter python
          
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework
      - uses: ./.github/actions/test
        with:
          working-dir: test-framework
          test-env: greetings_prod
